server.port=${SERVER_PORT:8081}

spring.application.name=cf-backend
spring.main.banner-mode=off
logging.pattern.console=%clr([%d{yyyy-MM-dd HH:mm:ss.SSS}]){yellow} %clr([%thread]){cyan} %clr([%X{X-REQUEST-ID}]){magenta} %clr(%-5level){highlight} %clr(%logger{36}){bold,blue} - %msg%n

debug=true
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.oauth2=TRACE

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.datasource.url=jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:cf-db}
spring.datasource.username=${DATABASE_USERNAME:cf-user}
spring.datasource.password=${DATABASE_PASSWORD:cf-password}

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}